/*
 * This file is generated by jOOQ.
 */
package com.bros.foodorderingsystem.model;


import com.bros.foodorderingsystem.model.tables.Item;
import com.bros.foodorderingsystem.model.tables.Order;
import com.bros.foodorderingsystem.model.tables.OrderItems;
import com.bros.foodorderingsystem.model.tables.OrderRating;
import com.bros.foodorderingsystem.model.tables.Student;
import com.bros.foodorderingsystem.model.tables.Vendor;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.item</code>.
     */
    public final Item ITEM = Item.ITEM;

    /**
     * The table <code>public.order</code>.
     */
    public final Order ORDER = Order.ORDER;

    /**
     * The table <code>public.order_items</code>.
     */
    public final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>public.order_rating</code>.
     */
    public final OrderRating ORDER_RATING = OrderRating.ORDER_RATING;

    /**
     * The table <code>public.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.vendor</code>.
     */
    public final Vendor VENDOR = Vendor.VENDOR;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Item.ITEM,
            Order.ORDER,
            OrderItems.ORDER_ITEMS,
            OrderRating.ORDER_RATING,
            Student.STUDENT,
            Vendor.VENDOR);
    }
}
