/*
 * This file is generated by jOOQ.
 */
package com.bros.fooforderingsystem.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItems implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private UUID          orderId;
    private UUID          itemId;
    private Integer       quantity;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public OrderItems() {}

    public OrderItems(OrderItems value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.itemId = value.itemId;
        this.quantity = value.quantity;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public OrderItems(
        UUID          id,
        UUID          orderId,
        UUID          itemId,
        Integer       quantity,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.orderId = orderId;
        this.itemId = itemId;
        this.quantity = quantity;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.order_items.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.order_items.id</code>.
     */
    public OrderItems setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.order_items.order_id</code>.
     */
    public UUID getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>public.order_items.order_id</code>.
     */
    public OrderItems setOrderId(UUID orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Getter for <code>public.order_items.item_id</code>.
     */
    public UUID getItemId() {
        return this.itemId;
    }

    /**
     * Setter for <code>public.order_items.item_id</code>.
     */
    public OrderItems setItemId(UUID itemId) {
        this.itemId = itemId;
        return this;
    }

    /**
     * Getter for <code>public.order_items.quantity</code>.
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>public.order_items.quantity</code>.
     */
    public OrderItems setQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Getter for <code>public.order_items.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.order_items.created_at</code>.
     */
    public OrderItems setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.order_items.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.order_items.updated_at</code>.
     */
    public OrderItems setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrderItems other = (OrderItems) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!orderId.equals(other.orderId))
            return false;
        if (itemId == null) {
            if (other.itemId != null)
                return false;
        }
        else if (!itemId.equals(other.itemId))
            return false;
        if (quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!quantity.equals(other.quantity))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.itemId == null) ? 0 : this.itemId.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderItems (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(itemId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
