/*
 * This file is generated by jOOQ.
 */
package com.bros.fooforderingsystem.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Order implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private String        studentId;
    private UUID          vendorId;
    private UUID          itemId;
    private String        status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Order() {}

    public Order(Order value) {
        this.id = value.id;
        this.studentId = value.studentId;
        this.vendorId = value.vendorId;
        this.itemId = value.itemId;
        this.status = value.status;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Order(
        UUID          id,
        String        studentId,
        UUID          vendorId,
        UUID          itemId,
        String        status,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.studentId = studentId;
        this.vendorId = vendorId;
        this.itemId = itemId;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.order.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.order.id</code>.
     */
    public Order setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.order.student_id</code>.
     */
    public String getStudentId() {
        return this.studentId;
    }

    /**
     * Setter for <code>public.order.student_id</code>.
     */
    public Order setStudentId(String studentId) {
        this.studentId = studentId;
        return this;
    }

    /**
     * Getter for <code>public.order.vendor_id</code>.
     */
    public UUID getVendorId() {
        return this.vendorId;
    }

    /**
     * Setter for <code>public.order.vendor_id</code>.
     */
    public Order setVendorId(UUID vendorId) {
        this.vendorId = vendorId;
        return this;
    }

    /**
     * Getter for <code>public.order.item_id</code>.
     */
    public UUID getItemId() {
        return this.itemId;
    }

    /**
     * Setter for <code>public.order.item_id</code>.
     */
    public Order setItemId(UUID itemId) {
        this.itemId = itemId;
        return this;
    }

    /**
     * Getter for <code>public.order.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.order.status</code>.
     */
    public Order setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.order.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.order.created_at</code>.
     */
    public Order setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.order.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.order.updated_at</code>.
     */
    public Order setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Order other = (Order) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (studentId == null) {
            if (other.studentId != null)
                return false;
        }
        else if (!studentId.equals(other.studentId))
            return false;
        if (vendorId == null) {
            if (other.vendorId != null)
                return false;
        }
        else if (!vendorId.equals(other.vendorId))
            return false;
        if (itemId == null) {
            if (other.itemId != null)
                return false;
        }
        else if (!itemId.equals(other.itemId))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.studentId == null) ? 0 : this.studentId.hashCode());
        result = prime * result + ((this.vendorId == null) ? 0 : this.vendorId.hashCode());
        result = prime * result + ((this.itemId == null) ? 0 : this.itemId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Order (");

        sb.append(id);
        sb.append(", ").append(studentId);
        sb.append(", ").append(vendorId);
        sb.append(", ").append(itemId);
        sb.append(", ").append(status);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
