/*
 * This file is generated by jOOQ.
 */
package com.bros.fooforderingsystem.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRating implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private UUID          orderId;
    private Integer       rating;
    private String        comment;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public OrderRating() {}

    public OrderRating(OrderRating value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.rating = value.rating;
        this.comment = value.comment;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public OrderRating(
        UUID          id,
        UUID          orderId,
        Integer       rating,
        String        comment,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.orderId = orderId;
        this.rating = rating;
        this.comment = comment;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.order_rating.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.order_rating.id</code>.
     */
    public OrderRating setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.order_rating.order_id</code>.
     */
    public UUID getOrderId() {
        return this.orderId;
    }

    /**
     * Setter for <code>public.order_rating.order_id</code>.
     */
    public OrderRating setOrderId(UUID orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * Getter for <code>public.order_rating.rating</code>.
     */
    public Integer getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>public.order_rating.rating</code>.
     */
    public OrderRating setRating(Integer rating) {
        this.rating = rating;
        return this;
    }

    /**
     * Getter for <code>public.order_rating.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for <code>public.order_rating.comment</code>.
     */
    public OrderRating setComment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Getter for <code>public.order_rating.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.order_rating.created_at</code>.
     */
    public OrderRating setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.order_rating.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.order_rating.updated_at</code>.
     */
    public OrderRating setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrderRating other = (OrderRating) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (orderId == null) {
            if (other.orderId != null)
                return false;
        }
        else if (!orderId.equals(other.orderId))
            return false;
        if (rating == null) {
            if (other.rating != null)
                return false;
        }
        else if (!rating.equals(other.rating))
            return false;
        if (comment == null) {
            if (other.comment != null)
                return false;
        }
        else if (!comment.equals(other.comment))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.orderId == null) ? 0 : this.orderId.hashCode());
        result = prime * result + ((this.rating == null) ? 0 : this.rating.hashCode());
        result = prime * result + ((this.comment == null) ? 0 : this.comment.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderRating (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(rating);
        sb.append(", ").append(comment);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
