/*
 * This file is generated by jOOQ.
 */
package com.bros.fooforderingsystem.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vendor implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private String        name;
    private String        email;
    private String        location;
    private Boolean       acceptingorders;
    private String        qrcode;
    private String        shopimage;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Vendor() {}

    public Vendor(Vendor value) {
        this.id = value.id;
        this.name = value.name;
        this.email = value.email;
        this.location = value.location;
        this.acceptingorders = value.acceptingorders;
        this.qrcode = value.qrcode;
        this.shopimage = value.shopimage;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Vendor(
        UUID          id,
        String        name,
        String        email,
        String        location,
        Boolean       acceptingorders,
        String        qrcode,
        String        shopimage,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.location = location;
        this.acceptingorders = acceptingorders;
        this.qrcode = qrcode;
        this.shopimage = shopimage;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.vendor.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.vendor.id</code>.
     */
    public Vendor setId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.vendor.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.vendor.name</code>.
     */
    public Vendor setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.vendor.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.vendor.email</code>.
     */
    public Vendor setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.vendor.location</code>.
     */
    public String getLocation() {
        return this.location;
    }

    /**
     * Setter for <code>public.vendor.location</code>.
     */
    public Vendor setLocation(String location) {
        this.location = location;
        return this;
    }

    /**
     * Getter for <code>public.vendor.acceptingorders</code>.
     */
    public Boolean getAcceptingorders() {
        return this.acceptingorders;
    }

    /**
     * Setter for <code>public.vendor.acceptingorders</code>.
     */
    public Vendor setAcceptingorders(Boolean acceptingorders) {
        this.acceptingorders = acceptingorders;
        return this;
    }

    /**
     * Getter for <code>public.vendor.qrcode</code>.
     */
    public String getQrcode() {
        return this.qrcode;
    }

    /**
     * Setter for <code>public.vendor.qrcode</code>.
     */
    public Vendor setQrcode(String qrcode) {
        this.qrcode = qrcode;
        return this;
    }

    /**
     * Getter for <code>public.vendor.shopimage</code>.
     */
    public String getShopimage() {
        return this.shopimage;
    }

    /**
     * Setter for <code>public.vendor.shopimage</code>.
     */
    public Vendor setShopimage(String shopimage) {
        this.shopimage = shopimage;
        return this;
    }

    /**
     * Getter for <code>public.vendor.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.vendor.created_at</code>.
     */
    public Vendor setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.vendor.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.vendor.updated_at</code>.
     */
    public Vendor setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Vendor other = (Vendor) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (email == null) {
            if (other.email != null)
                return false;
        }
        else if (!email.equals(other.email))
            return false;
        if (location == null) {
            if (other.location != null)
                return false;
        }
        else if (!location.equals(other.location))
            return false;
        if (acceptingorders == null) {
            if (other.acceptingorders != null)
                return false;
        }
        else if (!acceptingorders.equals(other.acceptingorders))
            return false;
        if (qrcode == null) {
            if (other.qrcode != null)
                return false;
        }
        else if (!qrcode.equals(other.qrcode))
            return false;
        if (shopimage == null) {
            if (other.shopimage != null)
                return false;
        }
        else if (!shopimage.equals(other.shopimage))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.location == null) ? 0 : this.location.hashCode());
        result = prime * result + ((this.acceptingorders == null) ? 0 : this.acceptingorders.hashCode());
        result = prime * result + ((this.qrcode == null) ? 0 : this.qrcode.hashCode());
        result = prime * result + ((this.shopimage == null) ? 0 : this.shopimage.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vendor (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(location);
        sb.append(", ").append(acceptingorders);
        sb.append(", ").append(qrcode);
        sb.append(", ").append(shopimage);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
