/*
 * This file is generated by jOOQ.
 */
package com.bros.fooforderingsystem.model;


import com.bros.fooforderingsystem.model.tables.Item;
import com.bros.fooforderingsystem.model.tables.Order;
import com.bros.fooforderingsystem.model.tables.OrderItems;
import com.bros.fooforderingsystem.model.tables.OrderRating;
import com.bros.fooforderingsystem.model.tables.Student;
import com.bros.fooforderingsystem.model.tables.Vendor;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.item</code>.
     */
    public static final Item ITEM = Item.ITEM;

    /**
     * The table <code>public.order</code>.
     */
    public static final Order ORDER = Order.ORDER;

    /**
     * The table <code>public.order_items</code>.
     */
    public static final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>public.order_rating</code>.
     */
    public static final OrderRating ORDER_RATING = OrderRating.ORDER_RATING;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.vendor</code>.
     */
    public static final Vendor VENDOR = Vendor.VENDOR;
}
