/*
 * This file is generated by jOOQ.
 */
package com.bros.foodorderingsystem.model.tables.records;


import com.bros.foodorderingsystem.model.tables.OrderItems;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItemsRecord extends UpdatableRecordImpl<OrderItemsRecord> implements Record6<UUID, UUID, UUID, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order_items.id</code>.
     */
    public OrderItemsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.order_items.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.order_items.order_id</code>.
     */
    public OrderItemsRecord setOrderId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.order_items.order_id</code>.
     */
    public UUID getOrderId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.order_items.item_id</code>.
     */
    public OrderItemsRecord setItemId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.order_items.item_id</code>.
     */
    public UUID getItemId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.order_items.quantity</code>.
     */
    public OrderItemsRecord setQuantity(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.order_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.order_items.created_at</code>.
     */
    public OrderItemsRecord setCreatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.order_items.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.order_items.updated_at</code>.
     */
    public OrderItemsRecord setUpdatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.order_items.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, UUID, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, UUID, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return OrderItems.ORDER_ITEMS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return OrderItems.ORDER_ITEMS.ORDER_ID;
    }

    @Override
    public Field<UUID> field3() {
        return OrderItems.ORDER_ITEMS.ITEM_ID;
    }

    @Override
    public Field<Integer> field4() {
        return OrderItems.ORDER_ITEMS.QUANTITY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return OrderItems.ORDER_ITEMS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return OrderItems.ORDER_ITEMS.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getOrderId();
    }

    @Override
    public UUID component3() {
        return getItemId();
    }

    @Override
    public Integer component4() {
        return getQuantity();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getOrderId();
    }

    @Override
    public UUID value3() {
        return getItemId();
    }

    @Override
    public Integer value4() {
        return getQuantity();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public OrderItemsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public OrderItemsRecord value2(UUID value) {
        setOrderId(value);
        return this;
    }

    @Override
    public OrderItemsRecord value3(UUID value) {
        setItemId(value);
        return this;
    }

    @Override
    public OrderItemsRecord value4(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public OrderItemsRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public OrderItemsRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public OrderItemsRecord values(UUID value1, UUID value2, UUID value3, Integer value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemsRecord
     */
    public OrderItemsRecord() {
        super(OrderItems.ORDER_ITEMS);
    }

    /**
     * Create a detached, initialised OrderItemsRecord
     */
    public OrderItemsRecord(UUID id, UUID orderId, UUID itemId, Integer quantity, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(OrderItems.ORDER_ITEMS);

        setId(id);
        setOrderId(orderId);
        setItemId(itemId);
        setQuantity(quantity);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
