/*
 * This file is generated by jOOQ.
 */
package com.bros.foodorderingsystem.model.tables.records;


import com.bros.foodorderingsystem.model.tables.Vendor;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendorRecord extends UpdatableRecordImpl<VendorRecord> implements Record9<UUID, String, String, String, Boolean, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.vendor.id</code>.
     */
    public VendorRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.vendor.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.vendor.name</code>.
     */
    public VendorRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.vendor.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.vendor.email</code>.
     */
    public VendorRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.vendor.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.vendor.location</code>.
     */
    public VendorRecord setLocation(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.vendor.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.vendor.acceptingorders</code>.
     */
    public VendorRecord setAcceptingorders(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.vendor.acceptingorders</code>.
     */
    public Boolean getAcceptingorders() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.vendor.qrcode</code>.
     */
    public VendorRecord setQrcode(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.vendor.qrcode</code>.
     */
    public String getQrcode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.vendor.shopimage</code>.
     */
    public VendorRecord setShopimage(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.vendor.shopimage</code>.
     */
    public String getShopimage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.vendor.created_at</code>.
     */
    public VendorRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.vendor.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.vendor.updated_at</code>.
     */
    public VendorRecord setUpdatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.vendor.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, String, String, String, Boolean, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, String, String, String, Boolean, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Vendor.VENDOR.ID;
    }

    @Override
    public Field<String> field2() {
        return Vendor.VENDOR.NAME;
    }

    @Override
    public Field<String> field3() {
        return Vendor.VENDOR.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return Vendor.VENDOR.LOCATION;
    }

    @Override
    public Field<Boolean> field5() {
        return Vendor.VENDOR.ACCEPTINGORDERS;
    }

    @Override
    public Field<String> field6() {
        return Vendor.VENDOR.QRCODE;
    }

    @Override
    public Field<String> field7() {
        return Vendor.VENDOR.SHOPIMAGE;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Vendor.VENDOR.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Vendor.VENDOR.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getLocation();
    }

    @Override
    public Boolean component5() {
        return getAcceptingorders();
    }

    @Override
    public String component6() {
        return getQrcode();
    }

    @Override
    public String component7() {
        return getShopimage();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getLocation();
    }

    @Override
    public Boolean value5() {
        return getAcceptingorders();
    }

    @Override
    public String value6() {
        return getQrcode();
    }

    @Override
    public String value7() {
        return getShopimage();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public VendorRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public VendorRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public VendorRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public VendorRecord value4(String value) {
        setLocation(value);
        return this;
    }

    @Override
    public VendorRecord value5(Boolean value) {
        setAcceptingorders(value);
        return this;
    }

    @Override
    public VendorRecord value6(String value) {
        setQrcode(value);
        return this;
    }

    @Override
    public VendorRecord value7(String value) {
        setShopimage(value);
        return this;
    }

    @Override
    public VendorRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public VendorRecord value9(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public VendorRecord values(UUID value1, String value2, String value3, String value4, Boolean value5, String value6, String value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VendorRecord
     */
    public VendorRecord() {
        super(Vendor.VENDOR);
    }

    /**
     * Create a detached, initialised VendorRecord
     */
    public VendorRecord(UUID id, String name, String email, String location, Boolean acceptingorders, String qrcode, String shopimage, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Vendor.VENDOR);

        setId(id);
        setName(name);
        setEmail(email);
        setLocation(location);
        setAcceptingorders(acceptingorders);
        setQrcode(qrcode);
        setShopimage(shopimage);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
